/**
 * ONE-TIME SEED ROUTE
 * Hit POST /api/seed?secret=seed-global-2026 to populate Supabase with data.
 * DELETE this file after seeding is complete.
 */
import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";

const SEED_SECRET = "seed-global-2026";

export async function POST(req: NextRequest) {
  const secret = req.nextUrl.searchParams.get("secret");
  if (secret !== SEED_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const results: Record<string, unknown> = {};

  // ── Users ──────────────────────────────────────────────────────────────────
  const users = [
    {
      id: "usr_admin_001",
      name: "Ashwin",
      email: "ashwin@global-dubai.com",
      password: "$2a$10$wpIVNMF03f9LfA2dIQkimep65ZNWe5XPA0YR.RDbqT2jc4EJSo4ym",
      role: "admin",
      phone: "",
      disabled: false,
      created_at: "2026-01-01T00:00:00.000Z",
      last_login_at: null,
    },
  ];
  const { error: usersErr } = await supabase.from("users").upsert(users, { onConflict: "id" });
  results.users = usersErr ? `ERROR: ${usersErr.message}` : "OK";

  // ── Candidates ─────────────────────────────────────────────────────────────
  const candidates = [
    { id: "cand_001", status: "completed", partner: "Challenger Grey", client_name: "Talogy", candidate_name: "Joanna Rodrigues", level_of_support: "Mid-High", lead_coach: "Saima", support: "Celeste", email: "joanna_0509@yahoo.co.in", whatsapp: "", linkedin: "https://www.linkedin.com/in/joanna-rodrigues-32b8a2116", duration: "3 Months (8 Sessions)", date_started: "2026-03-09", end_date: null, sessions_completed: 3, notes: "Waiting for her to send in her updated CV and LinkedIn, will then have the DiSC session.", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: true }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-03-09T00:00:00.000Z", updated_at: "2026-05-08T07:25:17.249Z", updated_by: "usr_admin_001" },
    { id: "cand_002", status: "active", partner: "Challenger Grey", client_name: "University Support", candidate_name: "Rachael Phelps", level_of_support: "Mid-High", lead_coach: "Iyas (External Global Coach)", support: "Ankit", email: "rphelps@hesss.com", whatsapp: "(971) 50 357 8897", linkedin: "http://linkedin.com/in/rachael-rose-phelps-262431152", duration: "3 Months", date_started: "2026-03-12", end_date: "2026-06-12", sessions_completed: 5, notes: "", disc_style: "", job_status: null, new_company: null, new_placement: "", position: "", sector: "", old_placement: "", progress: { introductorySession: true, cvSessions: true, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-03-12T00:00:00.000Z", updated_at: "2026-05-06T09:26:55.258Z", updated_by: "usr_admin_001" },
    { id: "cand_003", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Owais Masood", level_of_support: "Low", lead_coach: "Ashwin, Saima", support: "Celeste", email: "owaismasood@gmail.com", whatsapp: "3335145590", linkedin: "", duration: "3 Months", date_started: "2026-04-08", end_date: null, sessions_completed: 3, notes: "LinkedIn session scheduled. Documents in the Drive", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: true, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-08T00:00:00.000Z", updated_at: "2026-05-07T08:18:51.986Z", updated_by: "usr_admin_001" },
    { id: "cand_004", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Wardeh Tariq", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Ankit", email: "wardehsoomro@gmail.com", whatsapp: "3155222138", linkedin: "", duration: "3 Months", date_started: "2026-04-07", end_date: null, sessions_completed: 2, notes: "", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-07T00:00:00.000Z", updated_at: "2026-04-07T00:00:00.000Z", updated_by: null },
    { id: "cand_005", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Muhammad Shahzaib Siddiqui", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Celeste", email: "shahzaibsiddiqui.93@hotmail.com", whatsapp: "3493371026", linkedin: "", duration: "3 Months", date_started: "2026-04-10", end_date: null, sessions_completed: 2, notes: "CV session complete, next session is for LinkedIn. Documents in the Drive", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: true, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-10T00:00:00.000Z", updated_at: "2026-04-10T00:00:00.000Z", updated_by: null },
    { id: "cand_006", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Saleha Kamran", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Sarah", email: "anotherrartist@gmail.com", whatsapp: "92 323 5075056", linkedin: "https://www.linkedin.com/in/saleha-kamran/", duration: "3 Months", date_started: "2026-04-06", end_date: "2026-06-06", sessions_completed: 3, notes: "DiSC done", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-06T00:00:00.000Z", updated_at: "2026-04-06T00:00:00.000Z", updated_by: null },
    { id: "cand_007", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Yasir Qadeer", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Ankit", email: "yasirqadeer86@yahoo.com", whatsapp: "3345022589", linkedin: "", duration: "3 Months", date_started: null, end_date: null, sessions_completed: 0, notes: "", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: false, cvSessions: false, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-01T00:00:00.000Z", updated_at: "2026-04-01T00:00:00.000Z", updated_by: null },
    { id: "cand_008", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Fahad Daniyal", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Sarah", email: "daniyal0912@gmail.com", whatsapp: "923101377739", linkedin: "https://www.linkedin.com/in/fahaddaniyall/", duration: "3 Months", date_started: "2026-04-15", end_date: "2026-06-15", sessions_completed: 1, notes: "Session has been rescheduled (May 11-15). CV needs review, and unresponsive to follow ups", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: false, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-15T00:00:00.000Z", updated_at: "2026-04-15T00:00:00.000Z", updated_by: null },
    { id: "cand_009", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Bilal Ibrar", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Mehvish", email: "bilal.ibrar@gmail.com", whatsapp: "3335151247", linkedin: "https://www.linkedin.com/in/bilalibrar/", duration: "3 Months", date_started: "2026-04-10", end_date: "2026-06-10", sessions_completed: 3, notes: "", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-10T00:00:00.000Z", updated_at: "2026-04-10T00:00:00.000Z", updated_by: null },
    { id: "cand_010", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Komal Waseem", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Mehvish", email: "ko5890@gmail.com", whatsapp: "923425965560", linkedin: "https://www.linkedin.com/in/komal-waseem/", duration: "3 Months", date_started: "2026-04-14", end_date: "2026-06-15", sessions_completed: 3, notes: "", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-14T00:00:00.000Z", updated_at: "2026-04-14T00:00:00.000Z", updated_by: null },
    { id: "cand_011", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Mirza Ahsan", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Celeste", email: "ahsanmirzamm@gmail.com", whatsapp: "3335375091", linkedin: "", duration: "3 Months", date_started: "2026-04-16", end_date: "2026-06-16", sessions_completed: 1, notes: "Post introductory mail sent", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: false, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-16T00:00:00.000Z", updated_at: "2026-04-16T00:00:00.000Z", updated_by: null },
    { id: "cand_012", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Ali Imran", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Ankit", email: "imran17788pk@gmail.com", whatsapp: "923329198434", linkedin: "", duration: "3 Months", date_started: "2026-04-23", end_date: null, sessions_completed: 1, notes: "", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: false, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-23T00:00:00.000Z", updated_at: "2026-04-23T00:00:00.000Z", updated_by: null },
    { id: "cand_013", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Saulat Mehmood", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Sarah", email: "saulat.m1989@gmail.com", whatsapp: "3412825271", linkedin: "https://www.linkedin.com/in/saulat-mehmood/", duration: "3 Months", date_started: "2026-04-23", end_date: "2026-06-23", sessions_completed: 1, notes: "Post introductory mail sent + follow up", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: false, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-23T00:00:00.000Z", updated_at: "2026-05-08T06:36:32.695Z", updated_by: "usr_admin_001" },
    { id: "cand_014", status: "active", partner: "Intoo US", client_name: "Epic Games", candidate_name: "Imran Khan", level_of_support: "Low", lead_coach: "Saima, Ashwin", support: "Mehvish", email: "imrankkofficial@gmail.com", whatsapp: "3339858607", linkedin: "https://www.linkedin.com/in/imraannkhann/", duration: "3 Months", date_started: null, end_date: null, sessions_completed: 1, notes: "", disc_style: "", job_status: null, new_company: null, new_placement: null, position: null, sector: null, old_placement: null, progress: { introductorySession: true, cvSessions: false, linkedinProfile: false, profiling: false, networkingPersonalBranding: false }, activities: [], disc_done: "Not Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2026-04-01T00:00:00.000Z", updated_at: "2026-05-07T20:29:07.951Z", updated_by: "usr_admin_001" },
    { id: "cand_015", status: "completed", partner: "Challenger Grey", client_name: "Aspen Technology", candidate_name: "Ahmed El Assal", level_of_support: "High", lead_coach: "Saima", support: "Ashwin", email: "ahmed.elassal.ge@gmail.com", whatsapp: "971 (54) 9931955", linkedin: "", duration: "3 Months", date_started: "2025-01-01", end_date: "2025-04-01", sessions_completed: 8, notes: "", disc_style: "iD", job_status: "Y", new_company: "Honewell", new_placement: "Honewell", position: "Executive Director | Corporate Enterprise Solutions", sector: "Industrial and Aerospace Technology", old_placement: "Aspen Technology", progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: true }, activities: [], disc_done: "Done", invoice_status: "Cleared", costing_status: "Done", created_at: "2025-01-01T00:00:00.000Z", updated_at: "2025-04-01T00:00:00.000Z", updated_by: null },
    { id: "cand_016", status: "completed", partner: "Challenger Grey", client_name: "Aspen Technology", candidate_name: "Andrew Sutherland", level_of_support: "High", lead_coach: "Saima", support: "Ashwin", email: "andrew.sutherland@saratoga-tech.com", whatsapp: "971 (50) 6585278", linkedin: "", duration: "3 Months", date_started: "2025-01-01", end_date: "2025-04-01", sessions_completed: 8, notes: "", disc_style: "iD", job_status: "Y", new_company: "Copper Leaf", new_placement: "Copper Leaf", position: "Senior Vice President Sales, Middle East, Africa & Asia Pacific, Japan", sector: "Enterprise software and management consulting", old_placement: "Aspen Technology", progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: true }, activities: [], disc_done: "Done", invoice_status: "Cleared", costing_status: "Done", created_at: "2025-01-01T00:00:00.000Z", updated_at: "2025-04-01T00:00:00.000Z", updated_by: null },
    { id: "cand_017", status: "completed", partner: "Challenger Grey", client_name: "Aspen Technology", candidate_name: "Marjorie Gahal", level_of_support: "High", lead_coach: "Saima", support: "Celeste", email: "marjgahal@gmail.com", whatsapp: "973 3809 8716", linkedin: "", duration: "3 Months", date_started: "2025-01-01", end_date: "2025-04-01", sessions_completed: 8, notes: "", disc_style: "", job_status: "Y", new_company: "National Aquaculture Group", new_placement: "National Aquaculture Group", position: "Sr. HR Generalist", sector: "Aquaculture", old_placement: "Aspen Technology", progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: true }, activities: [], disc_done: "Done", invoice_status: "Cleared", costing_status: "Done", created_at: "2025-01-01T00:00:00.000Z", updated_at: "2025-04-01T00:00:00.000Z", updated_by: null },
    { id: "cand_018", status: "completed", partner: "Challenger Grey", client_name: "NYU", candidate_name: "Tamara Johnson", level_of_support: "High", lead_coach: "Saima", support: "Mehvish", email: "tamaranjohnsonis@gmail.com", whatsapp: "", linkedin: "", duration: "3 Months", date_started: "2024-01-01", end_date: "2024-04-01", sessions_completed: 8, notes: "", disc_style: "iS", job_status: "Y", new_company: "Neom", new_placement: "Neom", position: "HR Policy Design Senior", sector: "Tourism, Energy, Mobility, Biotech", old_placement: "NYU", progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: true }, activities: [], disc_done: "Done", invoice_status: "Cleared", costing_status: "Done", created_at: "2024-01-01T00:00:00.000Z", updated_at: "2024-04-01T00:00:00.000Z", updated_by: null },
    { id: "cand_019", status: "active", partner: "Intoo US", client_name: "Sprinklr", candidate_name: "Mohamed Alkhatib", level_of_support: "Mid", lead_coach: "Moamer", support: "Ashwin", email: "mohamed2552@live.com", whatsapp: "971 52 903 5654", linkedin: "", duration: "3 Months", date_started: "2024-06-01", end_date: "2024-09-01", sessions_completed: 8, notes: "", disc_style: "", job_status: null, new_company: "Sirion", new_placement: "Sirion", position: "Senior Principal Solution Consultant", sector: "IT", old_placement: "Sprinklr", progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: true }, activities: [], disc_done: "Done", invoice_status: "Raised", costing_status: "Not Done", created_at: "2024-06-01T00:00:00.000Z", updated_at: "2026-05-08T06:30:23.418Z", updated_by: "usr_admin_001" },
    { id: "cand_020", status: "active", partner: "Intoo US", client_name: "Sprinklr", candidate_name: "Rami Soubra", level_of_support: "Mid", lead_coach: "Sharmila", support: "Ankit", email: "rami.soubra@gmail.com", whatsapp: "", linkedin: "", duration: "3 Months", date_started: "2024-06-01", end_date: "2024-09-01", sessions_completed: 8, notes: "Did not start", disc_style: "", job_status: null, new_company: "UnifyApps", new_placement: "UnifyApps", position: "Senior Solutions Consultant", sector: "IT & AI", old_placement: "Sprinklr", progress: { introductorySession: true, cvSessions: true, linkedinProfile: true, profiling: true, networkingPersonalBranding: true }, activities: [], disc_done: "Done", invoice_status: "Not Raised", costing_status: "Not Done", created_at: "2024-06-01T00:00:00.000Z", updated_at: "2026-05-08T06:30:12.769Z", updated_by: "usr_admin_001" },
  ];
  const { error: candidatesErr } = await supabase.from("candidates").upsert(candidates, { onConflict: "id" });
  results.candidates = candidatesErr ? `ERROR: ${candidatesErr.message}` : "OK";

  // ── Transitions ────────────────────────────────────────────────────────────
  const transitions = [
    { id: "trans_001", year: "2024", candidate_name: "Tamara Johnson", client_name: "NYU", lead_owner: "Challenger Grey", consultant_in_charge: "Saima", supports: "Mehvish", old_job: "NYU", new_placement: "Neom", new_job_title: "HR Policy Design Senior", email: "", phone: "" },
    { id: "trans_002", year: "2024", candidate_name: "Siddarth Rathore", client_name: "Sprinklr", lead_owner: "Intoo US", consultant_in_charge: "Israa", supports: "Mehvish, Ashwin", old_job: "Sprinklr", new_placement: "Virtusa", new_job_title: "Director of Business Consulting", email: "", phone: "" },
    { id: "trans_003", year: "2025", candidate_name: "Ayham", client_name: "Karrierehuset", lead_owner: "Karrierehuset", consultant_in_charge: "Being Aware", supports: "Ashwin", old_job: "", new_placement: "", new_job_title: "Freelancer Consultant", email: "", phone: "" },
    { id: "trans_004", year: "2025", candidate_name: "Ahmed El Assal", client_name: "Aspen Technology", lead_owner: "Challenger Grey", consultant_in_charge: "Saima", supports: "Ashwin, Ankit", old_job: "Aspen", new_placement: "Honewell", new_job_title: "Executive Director | Corporate Enterprise Solutions", email: "", phone: "" },
    { id: "trans_005", year: "2025", candidate_name: "Ashish", client_name: "Freshworks", lead_owner: "Intoo US", consultant_in_charge: "Sharmila", supports: "Ashwin", old_job: "Freshworks", new_placement: "Jumbo Electronics", new_job_title: "Lead Digital Architect", email: "", phone: "" },
    { id: "trans_006", year: "2025", candidate_name: "Eduard Rinas", client_name: "Wintershall", lead_owner: "v. Rundstedt & Partner", consultant_in_charge: "Saima", supports: "Mehvish", old_job: "Wintershall", new_placement: "UpStream24", new_job_title: "Founder & Managing Director", email: "", phone: "" },
    { id: "trans_007", year: "2025", candidate_name: "Marjorie Gahal", client_name: "Aspen Technology", lead_owner: "Challenger Grey", consultant_in_charge: "Saima", supports: "Celeste", old_job: "Aspen Technology", new_placement: "National Aquaculture Group", new_job_title: "Sr. HR Generalist", email: "", phone: "" },
    { id: "trans_008", year: "2025", candidate_name: "Rasha Farid", client_name: "Wintershall", lead_owner: "v. Rundstedt & Partner", consultant_in_charge: "Saima", supports: "Mehvish", old_job: "Wintershall", new_placement: "KUFPEC", new_job_title: "Senior Consultant Business Development", email: "", phone: "" },
    { id: "trans_009", year: "2025", candidate_name: "Andrew Sutherland", client_name: "Aspen Technology", lead_owner: "Challenger Grey", consultant_in_charge: "Saima", supports: "Ashwin", old_job: "Aspen", new_placement: "Copper Leaf", new_job_title: "Senior Vice President Sales, Middle East, Africa & Asia Pacific, Japan", email: "", phone: "" },
    { id: "trans_010", year: "2025", candidate_name: "Roman Ishmuratov", client_name: "Wintershall", lead_owner: "v. Rundstedt & Partner", consultant_in_charge: "Saima", supports: "Mehvish", old_job: "Wintershall", new_placement: "AIQ", new_job_title: "Technical Project Manager", email: "", phone: "" },
    { id: "trans_011", year: "2025", candidate_name: "Raveena Kooleri", client_name: "BlueFloat", lead_owner: "Lukkap", consultant_in_charge: "Saima", supports: "Mehvish", old_job: "BlueFloat", new_placement: "London Strategy (LS)", new_job_title: "Finance & HR Associate", email: "", phone: "" },
    { id: "trans_012", year: "2025", candidate_name: "Ricardo Leo Marques Rouxinol", client_name: "Wintershall", lead_owner: "v. Rundstedt & Partner", consultant_in_charge: "Ashwin", supports: "Celeste, Mehvish", old_job: "Wintershall", new_placement: "Arverne", new_job_title: "Senior Drilling Engineer", email: "", phone: "" },
  ];
  const { error: transitionsErr } = await supabase.from("transitions").upsert(transitions, { onConflict: "id" });
  results.transitions = transitionsErr ? `ERROR: ${transitionsErr.message}` : "OK";

  // ── Companies ──────────────────────────────────────────────────────────────
  const companies = [
    { id: "comp_001", company_name: "Saudi Aramco", industry: "Oil & Gas", website: "https://www.aramco.com/en", point_of_contact: "Monika Pfingstl, Ashleigh Hurford", poc_linkedin: "https://www.linkedin.com/in/monika-pfingstl-23726130", poc_location: "UAE, UK", notes: "" },
    { id: "comp_002", company_name: "Abu Dhabi National Oil Company (ADNOC)", industry: "Oil & Gas", website: "https://www.adnoc.ae/", point_of_contact: "Sara H., Premkumar Rajendran, Hussein Mustafa", poc_linkedin: "https://www.linkedin.com/in/premkumar-rajendran-4270bbb9", poc_location: "UAE", notes: "Premkumar- Oil & Gas recruiter. Hussein- Senior Talent Acquisition Partner" },
    { id: "comp_003", company_name: "Qatar Energy (Qatar Petroleum)", industry: "All three", website: "https://www.qatarenergy.qa/en/Pages/vHome.aspx", point_of_contact: "Amira El Sabeiny, Rabih Abdel Khalek, Abdulla Al-Khater, Shuhdi Hasan", poc_linkedin: "https://www.linkedin.com/in/amira-el-sabeiny-a32976aa", poc_location: "Qatar", notes: "Abdulla- Senior recruiter at Qatar Energy" },
    { id: "comp_004", company_name: "Kuwait Petroleum Corporation", industry: "Oil & Gas", website: "https://www.kpc.com.kw/", point_of_contact: "Naser Hajiri, Sawsan Borosli", poc_linkedin: "https://www.linkedin.com/in/naser-hajiri-199023b2", poc_location: "Singapore, Kuwait", notes: "" },
    { id: "comp_005", company_name: "ExxonMobil", industry: "Oil & Gas", website: "https://corporate.exxonmobil.com/", point_of_contact: "Phil Flick, Carson Kempinski T., Kinga Priskin-Teremi", poc_linkedin: "https://www.linkedin.com/in/phil-flick", poc_location: "USA, UAE, Hungary", notes: "" },
    { id: "comp_006", company_name: "Shell", industry: "All three", website: "https://www.shell.com/", point_of_contact: "Lama Alsariri, Samreen Yousuf", poc_linkedin: "https://www.linkedin.com/in/lama-alsariri-phri-44a618140", poc_location: "Oman, Pakistan", notes: "" },
    { id: "comp_007", company_name: "BP (British Petroleum)", industry: "Oil & Gas", website: "https://www.bp.com/", point_of_contact: "Bader Adel", poc_linkedin: "https://www.linkedin.com/in/baher-adel-18867991", poc_location: "Egypt", notes: "HR Director - BP Egypt" },
    { id: "comp_008", company_name: "Total Energies", industry: "All three", website: "https://totalenergies.com/", point_of_contact: "Duaa Rahman, Divya Misra", poc_linkedin: "https://www.linkedin.com/in/duaa-rahman-090963177", poc_location: "UAE, India", notes: "Recruitment Consultant" },
    { id: "comp_009", company_name: "Chevron", industry: "Oil & Gas", website: "https://www.chevron.com/", point_of_contact: "Chevron Venezuela Recruitment, Jamal Falah", poc_linkedin: "", poc_location: "Venezuela, Saudi", notes: "" },
    { id: "comp_010", company_name: "Occidental Petroleum", industry: "Oil & Gas", website: "https://www.oxy.com/", point_of_contact: "Sameeh Al Jufaili, Heather Ramirez, Barry Horgan", poc_linkedin: "https://www.linkedin.com/in/sameeh-al-jufaili-oxy-oman-628374110", poc_location: "Oman, USA, UK", notes: "Occidental Chemical/Petrochemical in ME region" },
    { id: "comp_011", company_name: "Eni", industry: "Energy", website: "https://www.eni.com/en-IT/home.html", point_of_contact: "Faraz Sattar, Luca Del Latte", poc_linkedin: "https://www.linkedin.com/in/farazsattar/", poc_location: "Canada, Italy", notes: "Faraz previously handled Eni Oman's recruitment" },
    { id: "comp_012", company_name: "Halliburton", industry: "Energy", website: "https://www.halliburton.com/en/home", point_of_contact: "Amnah Alzahmi", poc_linkedin: "https://www.linkedin.com/in/amnah-alzahmi-ab4175219", poc_location: "UAE", notes: "" },
    { id: "comp_013", company_name: "Baker Hughes", industry: "Energy", website: "https://www.bakerhughes.com/", point_of_contact: "Manoj Kumar, Jacqueline Koo", poc_linkedin: "https://www.linkedin.com/in/manojkumar1609", poc_location: "UAE, Malaysia", notes: "" },
    { id: "comp_014", company_name: "Siemens Energy", industry: "Energy", website: "https://www.siemens-energy.com/global/en/home.html", point_of_contact: "Ahmed Elghatas", poc_linkedin: "https://www.linkedin.com/in/ahmed-elghatas-27385873", poc_location: "UAE", notes: "" },
  ];
  const { error: companiesErr } = await supabase.from("companies").upsert(companies, { onConflict: "id" });
  results.companies = companiesErr ? `ERROR: ${companiesErr.message}` : "OK";

  // ── Headhunters ────────────────────────────────────────────────────────────
  const headhunters = [
    { id: "hh_001", name: "George Arockia", type: "Recruiter", specialization: "Oil & Gas", linkedin: "https://www.linkedin.com/in/george-arockia-06629b43", email: "", location: "UAE", notes: "" },
    { id: "hh_002", name: "Premkumar Rajendran", type: "Specialist", specialization: "Oil & Gas", linkedin: "https://www.linkedin.com/in/premkumar-rajendran-4270bbb9", email: "", location: "UAE", notes: "" },
    { id: "hh_003", name: "Rami Hassan", type: "Recruiter", specialization: "Oil & Gas", linkedin: "", email: "", location: "UAE", notes: "" },
    { id: "hh_004", name: "Sameeha Al Ghallabi", type: "Recruiter", specialization: "Oil & Gas", linkedin: "https://www.linkedin.com/in/sameeha-alghallabi", email: "", location: "UAE", notes: "" },
    { id: "hh_005", name: "Vin Mohan", type: "Recruiter", specialization: "Oil & Gas", linkedin: "https://www.linkedin.com/in/vin-mohan-a01b578b", email: "", location: "UAE", notes: "" },
    { id: "hh_006", name: "Anupama Paulose", type: "Recruiter", specialization: "Oil & Gas", linkedin: "https://www.linkedin.com/in/anupama-paulose-she-her-678595111", email: "", location: "UAE", notes: "" },
    { id: "hh_007", name: "Gary Ferguson", type: "Headhunter", specialization: "Oil & Gas", linkedin: "https://www.linkedin.com/in/gary-ferguson-0114a243", email: "", location: "UAE", notes: "" },
    { id: "hh_008", name: "Elisa Fields", type: "Headhunter", specialization: "Oil & Gas", linkedin: "https://www.linkedin.com/in/elisa-fields-0314134a", email: "", location: "International", notes: "Based in the UK" },
    { id: "hh_009", name: "Daria Sergeeva", type: "Headhunter", specialization: "Oil & Gas", linkedin: "https://www.linkedin.com/in/daria-sergeeva-1864a199", email: "", location: "UAE", notes: "" },
    { id: "hh_010", name: "Vinod K.M.", type: "Recruiter", specialization: "Energy", linkedin: "https://www.linkedin.com/in/vinod-k-m-20bb762", email: "", location: "UAE", notes: "" },
    { id: "hh_011", name: "Aline Kelly Fiorini", type: "Recruiter", specialization: "Energy", linkedin: "https://www.linkedin.com/in/akfiorini", email: "", location: "UAE", notes: "Mubadala Energy" },
    { id: "hh_012", name: "Natascha Marais", type: "Headhunter", specialization: "Energy", linkedin: "", email: "", location: "UAE", notes: "" },
    { id: "hh_013", name: "Anna Entwistle", type: "Recruiter", specialization: "Energy", linkedin: "", email: "", location: "International", notes: "Based in Germany / Siemens Energy" },
  ];
  const { error: hhErr } = await supabase.from("headhunters").upsert(headhunters, { onConflict: "id" });
  results.headhunters = hhErr ? `ERROR: ${hhErr.message}` : "OK";

  // ── Lists ──────────────────────────────────────────────────────────────────
  const { error: listsErr } = await supabase.from("lists").upsert({
    id: 1,
    partners: ["Challenger Grey", "Intoo US"],
    clients: ["Aspen Technology", "Epic Games", "NYU", "Sprinklr", "Talogy", "University Support"],
    coaches: ["Ashwin", "Iyas (External Global Coach)", "Moamer", "Saima", "Sharmila"],
    supports: ["Ankit", "Ashwin", "Celeste", "Mehvish", "Sarah"],
  }, { onConflict: "id" });
  results.lists = listsErr ? `ERROR: ${listsErr.message}` : "OK";

  return NextResponse.json({
    message: "Seed complete!",
    results,
  });
}
